language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
install:
    - pip install .
before_script:
    - cd test
    - pip install -r requirements_test.txt
script:
    - coverage run --source ropes test_ropes.py
after_success:
    - coverage report -m
    - coveralls
sudo: False
